@echo off
REM claude-drives-gemini seeding-login window (generated by setup/init.mjs). No debug port = no automation signal, so Google allows login.
REM Usage: run this script, log in to Google/Gemini manually, close the window, then run start-chrome.cmd. ASCII only (cmd reads ANSI codepage).
start "" "{{CHROME}}" --user-data-dir="{{PROFILE}}" {{PROXY_ARG}} --no-first-run --no-default-browser-check https://gemini.google.com/app
