#!/usr/bin/env bash
# claude-drives-gemini login-seeding window (generated by setup/init.mjs): NO debug port = no automation signal, so Google allows login.
# Usage: run this -> log into Google/Gemini manually -> close window -> run start-chrome.sh
"{{CHROME}}" --user-data-dir="{{PROFILE}}" {{PROXY_ARG}} --no-first-run --no-default-browser-check 'https://gemini.google.com/app'
