#!/usr/bin/env bash
# claude-drives-gemini dedicated automation Chrome launcher (generated by setup/init.mjs; idempotent)
curl -s --max-time 2 "http://127.0.0.1:{{PORT}}/json/version" >/dev/null 2>&1 && { echo "[claude-drives-gemini] Chrome {{PORT}} already running"; exit 0; }
nohup "{{CHROME}}" --remote-debugging-port={{PORT}} --remote-allow-origins='*' --user-data-dir="{{PROFILE}}" {{PROXY_ARG}} --no-first-run --no-default-browser-check 'https://gemini.google.com/app' >/dev/null 2>&1 &
