#!/usr/bin/env bash
# claude-drives-gemini dedicated automation Chrome launcher (generated by setup/init.mjs; idempotent)
curl -s --max-time 2 "http://127.0.0.1:{{PORT}}/json/version" >/dev/null 2>&1 && { echo "[claude-drives-gemini] Chrome {{PORT}} already running"; exit 0; }
# Port dead: reap leftover Chrome still holding this profile without the debug port (e.g. login window kept alive by background mode), else the port can never bind. Main browser untouched.
pkill -f -- "--user-data-dir={{PROFILE}}( |$)" 2>/dev/null && sleep 1
# Keep stderr in a log (not /dev/null): snap confinement / missing libs would otherwise die silently.
nohup "{{CHROME}}" --remote-debugging-port={{PORT}} --remote-allow-origins='*' --user-data-dir="{{PROFILE}}" {{PROXY_ARG}} --no-first-run --no-default-browser-check 'https://gemini.google.com/app' >/tmp/claude-drives-gemini-chrome.log 2>&1 &
