@echo off
REM claude-drives-gemini dedicated automation Chrome launcher (generated by setup/init.mjs; do not edit template placeholders)
REM Idempotent: if the port is already alive, reuse it. ASCII only: cmd.exe reads batch files in the ANSI codepage, non-ASCII breaks parsing.
powershell -NoProfile -Command "try{$null=Invoke-WebRequest -UseBasicParsing -TimeoutSec 2 http://127.0.0.1:{{PORT}}/json/version;exit 0}catch{exit 1}"
if %errorlevel%==0 (echo [claude-drives-gemini] Chrome {{PORT}} already running & exit /b 0)
start "" "{{CHROME}}" --remote-debugging-port={{PORT}} --remote-allow-origins=* --user-data-dir="{{PROFILE}}" {{PROXY_ARG}} --no-first-run --no-default-browser-check https://gemini.google.com/app
